### ISSUE TITLE
KiCad libraries

### ISSUE THREAD

**Issue by JAR4x4** [mridley/emuecu#2]
Hi @mridley !
I'm trying to open the KiCad project, I'm missing the following libraries:

device.lib
transistors.lib
conn.lib
linear.lib
regul.lib
cmos4000.lib

Is it possible to add them?
I'm using KiCad 5 btw..

Best regards 
Alex

**Comment by mridley** [comment]
I did the checked in version using kicad from 16.04 ubuntu which is 4.0.2, In 18.04 the version is 4.0.7 and while I can open and convert the schematic I am struggling to edit the pcb anymore. I don't think any libraries are missing per se, it is just that the libraries and symbols have been renamed.
I was planning on re-doing the pcb anyway using surface mount components so I may just redo it.

I can send you the gerber and drill files if you just want to make up a pcb ?

**Comment by mridley** [comment]
I have updated to Kicad 5.1.5 and have modified some library components. But you should be able to open it now. Can you give it a go ?

**Comment by JAR4x4** [comment]
Thanks for your reply! I will test and report back! 

BTW, I'm the guy with the questions on the Canberra UAV Facebook page :)

Alex

**Comment by JAR4x4** [comment]
Works perfectly now =)

A
